public class ChicagoStyleClamPizza Extends Pizza{
	
    public override void prepare(){
        System.debug('Preparing the Chicago Clam pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the Chicago Clam pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the Chicago Clam pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the Chicago Clam pizza...');
        System.debug('Done.');

    }
    
}