public class ChicagoStylePepperoniPizza extends Pizza{
	
     public override void prepare(){
        System.debug('Preparing the Chicago Pepperoni pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the Chicago Pepperoni pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the Chicago Pepperoni pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the Chicago Pepperoni pizza...');
        System.debug('Done.');

    }
    
}