public class ChicagoStyleCheesePizza extends Pizza{

    public override void prepare(){
        System.debug('Preparing the Chicago chesse pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the Chicago chesse pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the Chicago chesse pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the Chicago chesse pizza...');
        System.debug('Done.');

    }
    
}