public class ChicagoStyleVeglePizza Extends Pizza{
	
     public override void prepare(){
        System.debug('Preparing the Chicago Vegle pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the Chicago Vegle pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the Chicago Vegle pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the Chicago Vegle pizza...');
        System.debug('Done.');

    }
    
}