public class NYStylePepperoniPizza extends Pizza{
    
    public override void prepare(){
        System.debug('Preparing the NY PepperoniPizza pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the NY PepperoniPizza pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the NY PepperoniPizza pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the NY PepperoniPizza pizza...');
        System.debug('Done.');

    }

}