public class NYStyleClamPizza extends Pizza{

     public override void prepare(){
        System.debug('Preparing the NY Clam  pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the NY Clam  pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the NY Clam  pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the NY Clam  pizza...');
        System.debug('Done.');

    }
    
}