public class NYStyleCheesePizza extends Pizza{
	
    public override void prepare(){
        System.debug('Preparing the NY chesse pizza...');
        System.debug('Done.');
    }
    
    public override void bake(){
        System.debug('Baking the NY chesse pizza...');
        System.debug('Done.');
    }
    
    public override void cut(){
        System.debug('Cutting the NY chesse pizza...');
        System.debug('Done.');

    }
    
    public override void box(){
        System.debug('Boxing the NY chesse pizza...');
        System.debug('Done.');

    }
    
}